[package]
name = "http-rust-wstd"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata.component]
package = "component:http-rust-wstd"
# This tells cargo-component to use a special adapter, which doesn't depend on
# `get-environment` or other things not present in the proxy world.
proxy = true

[dependencies]
# wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }
wstd = "0.6"
wit-bindgen = "0.48.0"
