package rvm:lambda@0.1.0;

@since(version = 0.1.0)
interface host {
    @since(version = 0.1.0)
    multiply: func(a: f32, b: f32) -> f32;
    @since(version = 0.1.0)
    client-secret: func() -> string;
    @since(version = 0.1.0)
    log: func(line: string);
    @since(version = 0.1.0)
    storage-put: func(path: string, contents: list<u8>) -> result<_, string>;
    @since(version = 0.1.0)
    storage-get: func(path: string) -> result<option<list<u8>>, string>;
    @since(version = 0.1.0)
    storage-list: func(prefix: string) -> result<list<string>, string>;
    @since(version = 0.1.0)
    kv-put: func(namespace: string, key: string, value: string) -> result<_, string>;
    @since(version = 0.1.0)
    kv-get: func(namespace: string, key: string) -> result<option<string>, string>;
    @since(version = 0.1.0)
    kv-list: func(namespace: string, prefix: string) -> result<list<tuple<string, string>>, string>;
}


@since(version = 0.1.0)
interface quic {
    @since(version = 0.1.0)
    use wasi:io/streams@0.2.8.{input-stream, output-stream};
    @since(version = 0.1.0)
    use wasi:io/poll@0.2.8.{pollable};
    @since(version = 0.1.0)
    use wasi:clocks/monotonic-clock@0.2.8.{duration};
    @since(version = 0.1.0)
    use wasi:sockets/network@0.2.8.{network, error-code, ip-socket-address};

    @since(version = 0.1.0)
    enum shutdown-type {
        /// Similar to `SHUT_RD` in POSIX.
        receive,
        /// Similar to `SHUT_WR` in POSIX.
        send,
        /// Similar to `SHUT_RDWR` in POSIX.
        both,
    }

    @since(version = 0.1.0)
    create-quic-socket: func(ip: ip-socket-address) -> result<quic-socket, error-code>;

    @since(version = 0.1.0)
    resource quic-socket {
        @since(version = 0.1.0)
        accept: func() -> result<quic-socket, error-code>;

        @since(version = 0.1.0)
        accept-bidirectional-stream: func() -> result<tuple<input-stream, output-stream>, error-code>;

        @since(version = 0.1.0)
        send-datagram: func(payload: list<u8>) -> result<_, error-code>;

        @since(version = 0.1.0)
        receive-datagram: func() -> result<list<u8>, error-code>;

        @since(version = 0.1.0)
        max-datagram-size: func() -> option<u64>;

        @since(version = 0.1.0)
        subscribe: func() -> pollable;

        @since(version = 0.1.0)
        local-address: func() -> result<ip-socket-address, error-code>;

        @since(version = 0.1.0)
        shutdown: func(shutdown-type: shutdown-type) -> result<_, error-code>;
    }
}

@since(version = 0.1.0)
world imports {
  import host;
}

@since(version = 0.1.0)
world rvm-http {
  include wasi:http/proxy@0.2.8;
  include imports;
}

@since(version = 0.1.0)
world rvm-quic {
  include imports;
  import quic;
}
